version: "3.9"

services:
  dind:
    build:
      context: .
    image: jamesmishra/dind
    privileged: true
    volumes:
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - type: volume
        source: dind_volume
        target: /var/lib/docker

volumes:
  dind_volume:
